### ISSUE TITLE
Visualization of Model Detection Results

### ISSUE THREAD

**Issue by ZZY-666** [lovelyqian/CDFSOD-benchmark#1]
Your article has benefited me a lot. Your job is great, and the test results are also excellent. But the visualization of the model detection results has not been made public yet. In order to better showcase the potential of the model, do you plan to make it public?

**Comment by AImind** [comment]
Thanks for your kind words. For visualization, you can reference [draw_bounding_boxes](https://github.com/mlzxy/devit/blob/main/demo/demo.py#L59) function in [devit](https://github.com/mlzxy/devit/tree/main).

**Comment by lovelyqian** [comment]
@ZZY-666 we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
