### ISSUE TITLE
difference between FSOD and CD-FSOD

### ISSUE THREAD

**Issue by userzhi** [lovelyqian/CDFSOD-benchmark#11]
@lovelyqian  hello, i am reading this paper and facing a question that what is the difference between FSOD and CD-FSOD.   To my understand, base class and novel class are from the same dataset in FSOD, however, base class and novel class are from different dataset in CD-FSOD.

**Comment by lovelyqian** [comment]
> @lovelyqian hello, i am reading this paper and facing a question that what is the difference between FSOD and CD-FSOD. To my understand, base class and novel class are from the same dataset in FSOD, however, base class and novel class are from different dataset in CD-FSOD.

hi @userzhi Thanks for your question. your understanding is right,  in the typical FSOD, since the base and novel classes are sampled from the same dataset, they could be basically regarded as the same domain, but CD-FSOD transfer from one dataset to another novel different dataset which is challenged by the domain shift issue.

**Comment by userzhi** [comment]
> > @lovelyqian hello, i am reading this paper and facing a question that what is the difference between FSOD and CD-FSOD. To my understand, base class and novel class are from the same dataset in FSOD, however, base class and novel class are from different dataset in CD-FSOD.
> 
> hi @userzhi Thanks for your question. your understanding is right, in the typical FSOD, since the base and novel classes are sampled from the same dataset, they could be basically regarded as the same domain, but CD-FSOD transfer from one dataset to another novel different dataset which is challenged by the domain shift issue.

@lovelyqian Thanks for your reply , i have read this paper, but i face another question that what is relation between open set and CD-FSOD

**Comment by lovelyqian** [comment]
@userzhi Basically, any novel concepts that hasn't been seen by model could be regarded as open set,  for example, open vocabulary is novel semantic labels to the model, FSOD(CD-FSOD) is the novel class with few examples to the models.

**Comment by lovelyqian** [comment]
@userzhi we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
