### ISSUE TITLE
Will the project work on Ubuntu 22.04?

### ISSUE THREAD

**Issue by MarineMehrabyan** [lovelyqian/CDFSOD-benchmark#12]
Will the project work on Ubuntu 22.04? Are there any versions of pytorch and cuda that will work on 22.04 version? And if not, can I run it on cpu?

**Comment by AImind** [comment]
Yes, the project can running on Ubuntu 22.04, and we are using CUDA version 11.6. You can check the requirements.txt file for the list of other necessary dependencies. Ubuntu 22.04 supports a variety of CUDA versions, and we highly recommend using a GPU for better performance. Please note that we haven't tested the project on CPU.
