### ISSUE TITLE
About the weights:vitl_0089999.pth 

### ISSUE THREAD

**Issue by renshouyu** [lovelyqian/CDFSOD-benchmark#13]
Hello, I would like to ask in the work of CD-FSOD, is the weight vitl_0089999.pth the weight after training from the coco10shot dataset?

**Comment by AImind** [comment]
This ckpt was trained on the COCO dataset, but not using the 10-shot setting. For more details, you can refer to this link: https://github.com/mlzxy/devit/blob/main/Downloads.md.
