### ISSUE TITLE
背景原型

### ISSUE THREAD

**Issue by renshouyu** [lovelyqian/CDFSOD-benchmark#14]
请问我看到在您的代码中统一使用了从coco数据集提取的背景原型，为什么不是根据不同的目标域数据集提取不同的背景原型啊？求大佬解答

**Comment by lovelyqian** [comment]
1. 我们的样本量比较少； 2. 对于特定target dataset，能够提取到的background信息比较单一； 整体效果不如coco中提取的效果好

**Comment by lovelyqian** [comment]
@renshouyu we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
