### ISSUE TITLE
FileNotFoundError in Test Dataset Due to Incorrect Annotations Path (train.json instead of test.json) in builtin.py

### ISSUE THREAD

**Issue by liukqchoco** [lovelyqian/CDFSOD-benchmark#16]
First, I would like to express my sincere gratitude for your excellent work and the comprehensive engineering effort behind your project! However, while reproducing your code, I encountered an issue with a `FileNotFoundError: [Errno 2] No such file or directory: 'datasets/NEUDET/test/pitted_surface_13.jpg'`. After carefully verifying my dataset and ensuring there were no errors, I proceeded to conduct a detailed review of your source code and spent a considerable amount of time debugging.

Eventually, I discovered a minor but critical issue in line 325 of `d2/data/datasets/builtin.py`. The relevant lines (323-325) are as follows:

```python
for dataset in datasets_name:
    _PREDEFINED_CD.append((f'{dataset}_train', f'{dataset}/train',f'{dataset}/annotations/train.json'))
    _PREDEFINED_CD.append((f'{dataset}_test', f'{dataset}/test',f'{dataset}/annotations/train.json'))
```

The `annotations` file in the last line should be `test.json` instead of `train.json`, as this causes persistent errors when loading the test dataset.

To help improve your project and ensure that others can benefit from its use, I have submitted a pull request addressing this issue. If you find the correction accurate, I kindly request that you accept the PR. I also wish continued success to your research team and your future endeavors. 

Thank you once again!

**Comment by AImind** [comment]
Thank you very much for your kind words and for sharing your feedback! I sincerely apologize for the oversight, and I will review the code thoroughly in the coming days.

I have reviewed and merged your pull request, and I am truly grateful for your valuable contribution.

**Comment by lovelyqian** [comment]
@liukqchoco  we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
