### ISSUE TITLE
_C是什么意思

### ISSUE THREAD

**Issue by arihara5** [lovelyqian/CDFSOD-benchmark#18]
detectron2/layers/deform_conv.py中使用了from detectron2 import _C代码，然后_C报错，请问这是怎样的用法呢，而且参考问题10我也没有得知到数据集的格式信息，能麻烦具体提供一下吗

**Comment by AImind** [comment]
You did not compile detectron2. Please follow [INSTALL.md](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) to install it.

split.py will be updated in the coming days.
