### ISSUE TITLE
实例权重模块

### ISSUE THREAD

**Issue by houyuchao** [lovelyqian/CDFSOD-benchmark#19]
您好文中提到的实例权重模块的代码部分在哪里呢？没有找到，可以提示一下吗

**Comment by lovelyqian** [comment]
InstReweight

**Comment by houyuchao** [comment]
> InstReweight
还是没找到，求助

**Comment by lzpyx** [comment]
/[detectron2](https://github.com/lovelyqian/CDFSOD-benchmark/tree/main/detectron2)/[modeling](https://github.com/lovelyqian/CDFSOD-benchmark/tree/main/detectron2/modeling)/[meta_arch](https://github.com/lovelyqian/CDFSOD-benchmark/tree/main/detectron2/modeling/meta_arch)
/devit.py

**Comment by lzpyx** [comment]
This module places at detectron2/modeling/meta_arch/devit.py

**Comment by houyuchao** [comment]
> This module places at detectron2/modeling/meta_arch/devit.py

感谢感谢已经找到

**Comment by houyuchao** [comment]
> This module places at detectron2/modeling/meta_arch/devit.
Learnable Instance Features这个也在这里面吗？没有发现啊
