### ISSUE TITLE
权重缺失

### ISSUE THREAD

**Issue by arihara5** [lovelyqian/CDFSOD-benchmark#21]
Some model parameters or buffers are not found in the checkpoint:
adapter.proto_center_attn.attention_weights.0.{bias, weight}
adapter.proto_center_attn.fc.{bias, weight}
bg_tokens.weight
class_weights.weight
domain_prompter.weight
prototype_classifier.linear.{bias, weight}
test_class_weight

**Comment by lzpyx** [comment]
You can get them in the training process. In testing, you don't need the domain_prompter.weight actually.
