### ISSUE TITLE
 from detectron2 import _C ImportError: cannot import name '_C' from 'detectron2' (D:\下载\CDFSOD-benchmark-main\detectron2\__init__.py)

### ISSUE THREAD

**Issue by houyuchao** [lovelyqian/CDFSOD-benchmark#23]
我发现没有_C文件啊在detectron2

**Comment by arihara5** [comment]
https://blog.csdn.net/qq_46345319/article/details/139928000?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522D5F266ED-C64D-4A82-8DA6-02F89F26C7E4%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=D5F266ED-C64D-4A82-8DA6-02F89F26C7E4&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_click~default-4-139928000-null-null.142^v100^pc_search_result_base9&utm_term=detectron2%E5%AE%89%E8%A3%85&spm=1018.2226.3001.4187你可以看看这个进行下载，我之前也出过_C找不到的问题

**Comment by arihara5** [comment]
[https://blog.csdn.net/qq_46345319/article/details/139928000?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522D5F266ED-C64D-4A82-8DA6-02F89F26C7E4%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=D5F266ED-C64D-4A82-8DA6-02F89F26C7E4&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_click~default-4-139928000-null-null.142^v100^pc_search_result_base9&utm_term=detectron2%E5%AE%89%E8%A3%85&spm=1018.2226.3001.4187   你可以看看这个进行下载，我之前也出过_C找不到的问题]

**Comment by AImind** [comment]
Did you successfully install detectron2?

**Comment by ZongYingLi** [comment]
先安装xformers，然后安装和电脑cuda对应的torch版本，安装别的包，然后在项目目录下pip  install setup.py -e.，如果出现了这种报错可能是torch的版本和detectron2的版本对不上，因为xformers会修改torch的版本
