### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by arihara5** [lovelyqian/CDFSOD-benchmark#24]
当我训练DIOR、FISH、NEU-DET、UODD数据集时，都出现了Key error的问题，例如KeyError: 'NEUDET_10shot'这样的问题，请问这是什么情况呢

**Comment by zhilingdong** [comment]
@arihara5  请问你解决了么？我也遇到了类似的问题

**Comment by arihara5** [comment]
检查lib/categories.py和detectron2/data/datasets/builtin.py这两个文件，找到datasets_name那一行，你就知道问题在哪了 @zhilingdong

**Comment by zhilingdong** [comment]
@arihara5   看到了，谢谢你

**Comment by tcourat** [comment]
Replace NEU-DET by NEUDET.

**Comment by lovelyqian** [comment]
@tcourat @arihara5 we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
