### ISSUE TITLE
windows系统下可以实现吗？

### ISSUE THREAD

**Issue by LimInGzE6** [lovelyqian/CDFSOD-benchmark#26]

**Comment by AImind** [comment]
Sorry, we only support Ubuntu systems with NVIDIA GPUs.

**Comment by lovelyqian** [comment]
@LimInGzE6 we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
