### ISSUE TITLE
数据可视化

### ISSUE THREAD

**Issue by FSJ-abc** [lovelyqian/CDFSOD-benchmark#27]
尊敬的作者，
您好！我使用您的代码进行了训练并且训练处结果了，但是由于我还对detectron代码框架不太熟悉，我想请问一下您训练好的代码大概应该怎么可视化呢？

**Comment by AImind** [comment]
You can obtain the bounding box information and draw a box on the image to visualize your result.

**Comment by lovelyqian** [comment]
@FSJ-abc we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
