### ISSUE TITLE
请求开源DEViT基线在此基准测试上的评估代码

### ISSUE THREAD

**Issue by Farenweh** [lovelyqian/CDFSOD-benchmark#4]
傅老师，您好！衷心祝贺您和您的团队完成了这项出色研究。CD-ViTO为CD-FSOD和在线适应建立了新的最佳，也为探索基础模型在跨域和小样本学习领域的潜力开了一个很好的头。

出于个人兴趣和学业，我尝试学习和复现这项研究，然而遇到了一些问题——无论是使用已开源的"Init_prototypes"，还是利用DEViT的代码从您提供的数据集和json标注建立原型并进行测试，DEViT在6个跨域数据集上的基准测试结果始终与论文中提供的表现有所出入。尽管我已经多次检查了数据集/config/原型提取代码和超参，仍未能找到问题所在。

因此，我希望您能够考虑开源用于在该基准测试上评估DEViT的代码，这肯定会帮助找到我的实验的问题，有利于我学习和理解您的工作。

再次祝贺和感谢您！

**Comment by lovelyqian** [comment]
您好，感谢对我们工作的关注，我们提供了DE-ViT-FT的复现代码（相较于直接infer来说对比更加公平一些），具体的操作： 1） Add --controller to main_results.sh, 2）bash main_results.sh。 公布代码之前我们都是做了三次重复实现的，几次不同的同学跑出来的结果都跟论文report的结果差不多，可以用我们的脚本再试试？

**Comment by lovelyqian** [comment]
@Farenweh we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851 (也有微信群，可以联系我加入）
