### ISSUE TITLE
Support for fast Inference

### ISSUE THREAD

**Issue by retazo0018** [lovelyqian/CDFSOD-benchmark#5]
Hi @lovelyqian,

Thanks for the great work.

I would like to know if there is a support for TensorRT or similar for fast inference to support real-time application.

Thanks

**Comment by lovelyqian** [comment]
Dear @retazo0018 , thanks for your attention and the question.  For now, we don't explore such fast inference.  It would be great if you plan to  and could give us some feedback!

**Comment by retazo0018** [comment]
Thanks @lovelyqian for your reply.

Sure, have you tried converting the CD-ViTO model be converted to ONNX format? I tried to export the model to ONNX but couldn't succeed.

**Comment by lovelyqian** [comment]
@retazo0018 Unfortunately, I haven't tried it (sorry that can't help you in the matter

**Comment by lovelyqian** [comment]
@retazo0018  we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
