### ISSUE TITLE
Finetuning using the entire train dataset

### ISSUE THREAD

**Issue by 44526653** [lovelyqian/CDFSOD-benchmark#7]
Hello. Thanks for the great work.

Instead of finetuning with k-shot, I want to finetune with the entire DIOR dataset(DIOR_train). What should I do?
First, I tried to create a .pkl file for DIOR_train using build_prototypes.sh. However, I’m not sure how much —num_prototypes should be set. Also, after running build_prototypes.sh, a total of 3 pkl files are created. I would appreciate it if you could also tell me which pkl file should be used to set the class_prototypes of the .yaml file.

**Comment by AImind** [comment]
Hello! Thank you for your interest in our work.

devit use a clustering algorithm when generating prototypes. If you use more than 10shot data, you can also set num_prototypes to 10 in [here](https://github.com/lovelyqian/CDFSOD-benchmark/blob/2a9f5df8d313b46204113c14e18ad90af5f9784c/build_prototypes.sh#L29). The file named ${dataset}_${shot}shot.vit${model}14.bbox.p${num_prototypes}.sk.pkl is the final prototypes file.

You can also refer to [devit](https://github.com/mlzxy/devit/blob/main/Tools.md) to adjust the strategy for generating prototypes.
