### ISSUE TITLE
在自己的数据集上复现遇到问题

### ISSUE THREAD

**Issue by wangqiudong** [lovelyqian/CDFSOD-benchmark#8]
谢谢您在别的issue的解答！
(cdfsod) h@hn:~/wang/projects/CDFSOD-benchmark$ bash build_prototypes.sh 
prototypes_init folder already exists.
PYTHONPATH: None
Using cache found in /home/h/.cache/torch/hub/facebookresearch_dinov2_main
/home/h/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/h/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/h/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")

Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

Found thing categories: 1
  0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]/home/h/wang/projects/CDFSOD-benchmark/detectron2/structures/boxes.py:158: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:230.)
  tensor = torch.as_tensor(tensor, dtype=torch.float32, device=device)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.19it/s]
shot: 87
Saving to prototypes_init/FISH_1shot.vitl14.bbox.pkl and prototypes_init/FISH_1shot.vitl14.bbox_ori.pkl
extract_instance_prototypes with vitl for 1shot FISH done, save at prototypes_init dir.
{'batch_size': 512,
 'device': 0,
 'epochs': 30,
 'inp': 'prototypes_init/FISH_1shot.vitl14.bbox.pkl',
 'momentum': 0.002,
 'normalize': 'yes',
 'num_prototypes': 1,
 'oneshot': False,
 'oneshot_sample_pool': 30,
 'queue_size': 8192,
 'save': 'yes',
 'save_tokens': 'no',
 'token_type': 'pat'}
load and preprocess dataset

Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

total tokens 87, num classes 1
learning prototypes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 111.67it/s]
self testing prototypes
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 2162.01it/s]
 --> Class Acc 
- fish = 1.0000
cls acc = 1.0000
   Overall = 1.0000
![Uploading 7b96c997bec484423b27b8e502a4f16.png…]()

label_names` are set to ['fish']
Saving to prototypes_init/FISH_1shot.vitl14.bbox.p1.sk.pkl
run_sinkhorn_cluster with vitl for 1shot FISH done, save at prototypes_init dir.
我把自己的数据集（单类别密集型，一张图能有100+标注框）放到FISH里面进行Build Prototypes，1_shot.json中有1张图，87个标注，这样是Build Prototypes成功了吗?但是FISH_1shot.vitb14.bbox.p1.sk.pkl大小是0kb,有些.sk.pkl大小几十kb，但是运行main_result.sh后ap只有0.2，目前复现遇到了瓶颈

**Comment by wangqiudong** [comment]
/
![Uploading 7b96c997bec484423b27b8e502a4f16.png…]()

**Comment by wangqiudong** [comment]
[09/25 10:38:22 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.01 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.010
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.028
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.023
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.021
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.163
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.122
[09/25 10:38:22 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 0.240 | 1.038  | 0.041  | 0.226 | 2.814 | 0.339 |
[09/25 10:38:22 d2.engine.defaults]: Evaluation results for FISH_test in csv format:
[09/25 10:38:22 d2.evaluation.testing]: copypaste: Task: bbox
[09/25 10:38:22 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[09/25 10:38:22 d2.evaluation.testing]: copypaste: 0.2396,1.0377,0.0414,0.2258,2.8144,0.3392
[09/25 10:38:22 d2.evaluation.testing]: ###################### ('AP', 0.23963226703211005) ######################

**Comment by AImind** [comment]
It appears that you are using all 87 instances in one figure. In our setup, 1 shot consists of just one instance. You may revise this and test again. 
While this issue could stem from other reasons, could you please provide your 1shot.json file?

**Comment by lovelyqian** [comment]
@wangqiudong  we just released the 1st CD-FSOD challenge under NTIRE CVPR25 workshop, may we invite you to join this as participant. More info could be find here: https://codalab.lisn.upsaclay.fr/competitions/21851
